# Generated by Django 5.2.4 on 2025-07-08 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, db_column='phoneNumber', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('link_precedence', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], db_column='linkPrecedence', default='primary', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deletedAt', null=True)),
                ('linked_contact', models.ForeignKey(blank=True, db_column='linkedId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_contacts', to='contacts.contact')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
